[theme]
primaryColor = "#4CAF50"
backgroundColor = "#F0F2F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#262730"
font = "sans serif"

[server]
port = 8501
headless = true
enableCORS = false

[browser]
serverAddress = "localhost"
serverPort = 8501